name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # Triggers on tags like v0.1.0, v1.2.3

jobs:
  call-workflow:
    uses: thespacedoctor/reusable-workflows/.github/workflows/publish.yml@main
